# "deepseek-r1:14b" "qwen3-vl:30b-a3b-thinking" "nemotron-3-nano:30b" "gpt-oss:20b" "qwen3:30b"
ollama_models:
  reasoning_model: "qwen3:30b"
  mini_model: "qwen3:30b"
  nano_model: "qwen3:30b"

ollama_params:
  reasoning_model:
    reasoning: true
    num_predict: 10240
    temperature: 0.15
    top_p: 0.9
    top_k: 40
    repeat_penalty: 1.25
    repeat_last_n: 256
    seed: 2026
    extra: {}
  mini_model:
    reasoning: true
    num_predict: 4096
    temperature: 0.4
    seed: 2026
    extra: {}
  nano_model:
    reasoning: false
    num_predict: 2048
    temperature: 0.2
    seed: 2026
    extra: {}

paths:
  input_abstracts: "abstracts_0001-1000.jsonl"
  curation_output_dir: "qwen3-30b-prod-0.15-0.9-40-1.25-256-0001-1000"